spring.application.name=auth-service
server.port=8087

# H2 transactionnel (profil par defaut)
spring.datasource.url=jdbc:h2:mem:auth-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

# JWT
app.jwt.secret=WellnessShopSecretKey2025AzureMLDropshippingCervicalPain
app.jwt.expiration=86400000

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
spring.cloud.config.enabled=false
spring.cloud.discovery.enabled=true

# Actuator
management.endpoints.web.exposure.include=*

# Java 21 Virtual Threads
spring.threads.virtual.enabled=true
