# Profil Azure App Service - auth-service (Java 21)
server.port=80
eureka.client.service-url.defaultZone=https://wellness-discovery.azurewebsites.net/eureka
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=wellness-auth.azurewebsites.net
spring.cloud.config.enabled=false

# H2 console desactive en production
spring.h2.console.enabled=false
spring.jpa.hibernate.ddl-auto=update

# JWT secret depuis Azure App Setting (injecte via variable env APP_JWT_SECRET)
app.jwt.secret=${APP_JWT_SECRET:WellnessShopSecretKey2025AzureMLDropshippingCervicalPain}

# Virtual threads Java 21
spring.threads.virtual.enabled=true
