package net.maaroufi.trackingservice.controllers;

import net.maaroufi.trackingservice.dto.BehaviorEventDTO;
import net.maaroufi.trackingservice.entities.BehaviorEvent;
import net.maaroufi.trackingservice.entities.ProductTrackingStats;
import net.maaroufi.trackingservice.services.TrackingService;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

@RestController
@RequestMapping("/api/tracking")
@CrossOrigin(origins = "*")
public class TrackingController {

    private final TrackingService trackingService;

    public TrackingController(TrackingService trackingService) {
        this.trackingService = trackingService;
    }

    /**
     * Main endpoint to ingest a behavior event.
     *
     * The browser sends this on every tracked action:
     *   - page load (PAGE_VIEW with UTM params from FB ad URL)
     *   - product view, click, add-to-cart, purchase, search
     *
     * The X-Session-Id header should be generated by the client and persisted
     * in localStorage so that anonymous sessions can be tracked across requests.
     */
    @PostMapping("/event")
    public ResponseEntity<Map<String, Object>> trackEvent(
            @RequestBody BehaviorEventDTO dto,
            @RequestHeader(value = "X-Session-Id", required = false) String headerSessionId) {

        // Assign or propagate session ID
        String sessionId = (headerSessionId != null && !headerSessionId.isBlank())
                ? headerSessionId
                : (dto.getSessionId() != null ? dto.getSessionId() : UUID.randomUUID().toString());
        dto.setSessionId(sessionId);

        BehaviorEvent saved = trackingService.ingestEvent(dto);

        Map<String, Object> response = new HashMap<>();
        response.put("eventId", saved.getId());
        response.put("sessionId", sessionId);
        response.put("serverTimestamp", saved.getServerTimestamp());

        return ResponseEntity.status(HttpStatus.ACCEPTED).body(response);
    }

    // ---- Product tracking stats endpoints ----

    /**
     * Returns aggregated tracking stats for a specific product.
     * Includes viewCount, totalViewDurationMs, averageViewDurationMs, lastViewedAt.
     */
    @GetMapping("/stats/product/{productId}")
    public ResponseEntity<ProductTrackingStats> getProductStats(@PathVariable Long productId) {
        ProductTrackingStats stats = trackingService.getProductStats(productId);
        if (stats == null) {
            return ResponseEntity.notFound().build();
        }
        return ResponseEntity.ok(stats);
    }

    /**
     * Returns stats for all tracked products, ordered by view count descending.
     */
    @GetMapping("/stats/products")
    public ResponseEntity<List<ProductTrackingStats>> getAllProductStats() {
        return ResponseEntity.ok(trackingService.getAllProductStats());
    }

    /**
     * Session close endpoint — called by the JS client on beforeunload or purchase confirmation.
     *
     * Persists the complete session item path (ordered list of productIds viewed)
     * back to all existing BehaviorEvents for this session.
     *
     * Payload example:
     * {
     *   "sessionId": "sess-abc",
     *   "sessionItemPath": [12, 45, 7],
     *   "exitEvent": "TRANSACTION_COMPLETE"
     * }
     */
    @PostMapping("/session/close")
    public ResponseEntity<Map<String, Object>> closeSession(
            @RequestBody Map<String, Object> body) {

        String sessionId = (String) body.get("sessionId");
        @SuppressWarnings("unchecked")
        List<Long> sessionItemPath = body.containsKey("sessionItemPath")
                ? (List<Long>) body.get("sessionItemPath")
                : null;
        String exitEvent = (String) body.getOrDefault("exitEvent", "");

        if (sessionId == null || sessionId.isBlank()) {
            return ResponseEntity.badRequest().body(Map.of("error", "sessionId is required"));
        }

        trackingService.closeSession(sessionId, sessionItemPath, exitEvent);

        Map<String, Object> response = new HashMap<>();
        response.put("sessionId", sessionId);
        response.put("status", "closed");
        return ResponseEntity.ok(response);
    }

    /**
     * Health check / info endpoint.
     */
    @GetMapping("/health")
    public ResponseEntity<Map<String, String>> health() {
        Map<String, String> status = new HashMap<>();
        status.put("service", "tracking-service");
        status.put("status", "UP");
        return ResponseEntity.ok(status);
    }
}
