package net.maaroufi.trackingservice.controllers;

import net.maaroufi.trackingservice.dto.BehaviorEventDTO;
import net.maaroufi.trackingservice.entities.BehaviorEvent;
import net.maaroufi.trackingservice.services.TrackingService;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

@RestController
@RequestMapping("/api/tracking")
@CrossOrigin(origins = "*")
public class TrackingController {

    private final TrackingService trackingService;

    public TrackingController(TrackingService trackingService) {
        this.trackingService = trackingService;
    }

    /**
     * Main endpoint to ingest a behavior event.
     *
     * The browser sends this on every tracked action:
     *   - page load (PAGE_VIEW with UTM params from FB ad URL)
     *   - product view, click, add-to-cart, purchase, search
     *
     * The X-Session-Id header should be generated by the client and persisted
     * in localStorage so that anonymous sessions can be tracked across requests.
     */
    @PostMapping("/event")
    public ResponseEntity<Map<String, Object>> trackEvent(
            @RequestBody BehaviorEventDTO dto,
            @RequestHeader(value = "X-Session-Id", required = false) String headerSessionId) {

        // Assign or propagate session ID
        String sessionId = (headerSessionId != null && !headerSessionId.isBlank())
                ? headerSessionId
                : (dto.getSessionId() != null ? dto.getSessionId() : UUID.randomUUID().toString());
        dto.setSessionId(sessionId);

        BehaviorEvent saved = trackingService.ingestEvent(dto);

        Map<String, Object> response = new HashMap<>();
        response.put("eventId", saved.getId());
        response.put("sessionId", sessionId);
        response.put("serverTimestamp", saved.getServerTimestamp());

        return ResponseEntity.status(HttpStatus.ACCEPTED).body(response);
    }

    /**
     * Health check / info endpoint.
     */
    @GetMapping("/health")
    public ResponseEntity<Map<String, String>> health() {
        Map<String, String> status = new HashMap<>();
        status.put("service", "tracking-service");
        status.put("status", "UP");
        return ResponseEntity.ok(status);
    }
}
