spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: r1
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customers/**
        - id: r2
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**
        - id: r3
          uri: lb://TRACKING-SERVICE
          predicates:
            - Path=/api/tracking/**
        - id: r4
          uri: lb://RECOMMENDATION-SERVICE
          predicates:
            - Path=/api/recommendations/**
        - id: r5
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
        - id: r6
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
