spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customers/**
        - id: r2
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**
        - id: r3
          uri: lb://TRACKING-SERVICE
          predicates:
            - Path=/api/tracking/**
        - id: r4
          uri: lb://RECOMMENDATION-SERVICE
          predicates:
            - Path=/api/recommendations/**
