# Profil Azure App Service - gateway-service
server.port=80
eureka.client.service-url.defaultZone=https://wellness-discovery.azurewebsites.net/eureka
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=wellness-gateway.azurewebsites.net
spring.cloud.config.enabled=false

# CORS : localhost dev + Azure Static Web Apps prod
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOriginPatterns[0]=http://localhost:4200
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOriginPatterns[1]=https://wellness-frontend.azurestaticapps.net
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true
