# Profil Azure App Service - discovery-service (Eureka Server)
server.port=80
eureka.instance.hostname=wellness-discovery.azurewebsites.net
eureka.instance.non-secure-port=80
eureka.instance.non-secure-port-enabled=true
eureka.instance.prefer-ip-address=false
# Desactiver auto-registration (c'est le serveur)
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
